# try:
#     raise ValueError("ouch")
# except ValueError as e:
#     print("Caught %s" % e)
